### ISSUE TITLE
Uncaught Exception RangeError in Socket

### ISSUE THREAD

**Issue by itsjimbo** [pilwon/node-ib#67]
Once in a great while, I get these, which is impossible to catch

```
RangeError: Invalid array length
    at Incoming.process (node_modules/ib/lib/incoming.js:1229:41)
    at Socket._onData (node_modules/ib/lib/socket.js:48:30)
    at Socket.<anonymous> (node_modules/ib/lib/socket.js:87:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)

```

**Comment by bfreis** [comment]
I just got the exact same error. Nothing out of the ordinary seem to have happened right before, at least not according to my logs - I'm logging every state transition in my connection, and I'm logging every error message.


node_modules/ib/lib/incoming.js:1229
      this._dataQueue = this._dataQueue.concat(dataQueueSnapshot);
                                        ^
RangeError: Invalid array length
    at Incoming.process (node_modules/ib/lib/incoming.js:1229:41)
    at Socket._onData (node_modules/ib/lib/socket.js:48:30)
    at Socket.<anonymous> (node_modules/ib/lib/socket.js:91:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
